version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    vendor: true

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
